### ISSUE TITLE
Remove base layer

### ISSUE THREAD

**Issue by OriginalSin** [ScanEx/Leaflet-IconLayers#1]
Хорошо бы иметь возможность отключения активной подложки - например путем снятия checkbox (настоящего) на текущей подложке.
 Иногда это позволяет легко обнаружить ошибки при отображении слоев например неожиданные zIndex

**Comment by zverev** [comment]
Она же при этом уберётся с карты. Вы уверены, что нам нужно такое поведение?
Для отладки можно просто добавить пустой слой примерно следующего содержания:

``` javascript
{
    layer: {
        onAdd: function() {},
        onRemove: function() {}
    },
    title: 'empty'
}
```

В issues в следующий раз предлагаю писать по-английски, чтобы остальные пользователи плагина нас понимали.

**Comment by OriginalSin** [comment]
Yes I want remove baseLayer from map

**Comment by zverev** [comment]
Create an empty layer and turn it on (use the code from above).

@aparshin, maybe we could implement this feature as one of widget's _behaviors_? Is it a fairly common use case?

**Comment by aparshin** [comment]
Empty base layer is relatively common case, but I think that manually added by user empty layer is good variant.
