### ISSUE TITLE
change3 in css leads to errors

### ISSUE THREAD

**Issue by saeed3068** [ScanEx/Leaflet-IconLayers#2]
Hey,

I tried to change part of the css source code as follow in order to locate the icon not in the bottom of the page.

.leaflet-iconLayers-layer {
    cursor: pointer;
    position: relative;
    bottom:390px;       **_I added this line to the code**_*
    width: 80px;
    height: 80px;
    background-color: #fff;
    background-repeat: no-repeat;
    background-size: cover;
    text-align: center;
    box-sizing: border-box;
    box-shadow: 0 0 5px #000;
}

After doing so, the icon moves upper on the page but it does not function as before. When I click on the it, it will be collapsed but it does not let me choose other base-maps. In other words, when I try to hover over other base maps, the table containing base maps will be closed quickly and does not let me to choose my favorite base map. 

any idea??

tnks,
Saeid

**Comment by aparshin** [comment]
Add the following CSS rule instead of your midification:

```
.leaflet-left .leaflet-control.leaflet-iconLayers {
    margin-bottom: 390px;
}
```

It will shift the whole control 390 pixels up.

**Comment by saeed3068** [comment]
Thanks, Aparshin
