### ISSUE TITLE
Adding a header to the page leads to a collapse of icons

### ISSUE THREAD

**Issue by saeed3068** [ScanEx/Leaflet-IconLayers#3]
I added a header to my html and after doing so I noticed that the basemap icon collapsed. I am wondering why it happens and how I can fix this?

![2](https://cloud.githubusercontent.com/assets/12058753/8409538/7f558b18-1e46-11e5-8b7a-08cfde9d35d7.JPG)

![1](https://cloud.githubusercontent.com/assets/12058753/8409476/2f25e822-1e46-11e5-9ab9-fa8c9c4c3aac.JPG)

**Comment by aparshin** [comment]
It doesn't look like a problem with the header. Could you upload your page somewhere and add a link here?

**Comment by saeed3068** [comment]
I uploaded js.css and html here: 
https://drive.google.com/folderview?id=0BxD4m9Tpwq2fflRQMkRhaUtndjZQbjJUM0c5TDI1eDJ4ek9wSUxmUHowc2lhNC1HVW40ejA&usp=drive_web

**Comment by aparshin** [comment]
Just fix the misprint in `test4.html`:

```
<dive id="header" style="position: fixed">
```

should be changed to 

```
<div id="header" style="position: fixed">
```

**Comment by saeed3068** [comment]
thank you so much
