### ISSUE TITLE
valid javascript

### ISSUE THREAD

**Issue by stefanocudini** [ScanEx/Leaflet-IconLayers#6]
this code is not recommended:
https://github.com/stefanocudini/Leaflet-IconLayers/blob/master/src/iconLayers.js#L176

JSHINT show:

```
W083: Don't make functions within a loop.
                }.bind(this));
```

**Comment by aparshin** [comment]
I've added all your changes from PR https://github.com/ScanEx/Leaflet-IconLayers/pull/4. I hope it doesn't complicate your work on PR!
