### ISSUE TITLE
.addTo(map) does not work?

### ISSUE THREAD

**Issue by chimaera8** [ScanEx/Leaflet-IconLayers#7]
Hey there,

first of all: Thanks for your work to build that Plugin! I totally like the idea. :)

However, I'm struggling with using it for my webmap. I came down to simple copy your example map in a .html file adapting the dependency paths....and I get a grey screen, independent of the browser I use. :/

You can insert the code here for testing purposes: http://www.play-hookey.com/htmltest/
And you'll probably get a grey map. The textbox in the top left is for testing purposes and tells where the code stops.

It currently stops before the provider-loop. But if I load the same providers.js file from a different place it continues until the last line, just not adding the control to the map.

Thank you so much for helping me out....it's probably a very simple error that I just cannot think of at the moment..

Best regards!

This is my code (practically identical to the example):

<!DOCTYPE html>
<html>
    <head>
        <title>Leflet-IconLayers demo</title>
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/leaflet/0.7.3/leaflet-src.js"></script>
        <script type="text/javascript" src="https://github.com/ScanEx/Leaflet-IconLayers/blob/master/examples/providers.js"></script>
        <script type="text/javascript" src="https://github.com/ScanEx/Leaflet-IconLayers/blob/master/src/iconLayers.js"></script>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet/0.7.3/leaflet.css">
        <link rel="stylesheet" href="https://github.com/ScanEx/Leaflet-IconLayers/blob/master/src/iconLayers.css">

```
    <style>
        body {
            margin: 0;
            padding: 0;
            width: 100%;
            height: 100%;
        }
        #map {
            position: absolute;
            top: 0;
            bottom: 0;
            left: 0;
            right: 0;
        }
         #testbox { position: absolute; top: 10px; left: 50px; z-index: 99; height: 20px }
    </style>
</head>
<body>
  <div id="map"></div>
    <div id="testbox">
     <p>Test:</p> </div>
    <script>

var map = L.map('map').setView([38.14, 19.33], 7);            

        var layers = [];
        document.getElementById("testbox").innerHTML = "map + layers";
        for (var providerId in providers) {
            layers.push(providers[providerId]);
        }

        document.getElementById("testbox").innerHTML = "for-loop";

        layers.push({
            layer: {
                onAdd: function() {},
                onRemove: function() {}
            },
            title: 'empty'
        })

        document.getElementById("testbox").innerHTML = "push";

        var ctrl = L.control.iconLayers(layers).addTo(map);

        document.getElementById("testbox").innerHTML = "added";
    </script>
</body>
```

</html>

**Comment by zverev** [comment]
Hi!

I've just copied your code, added libs from demo page and everything worked fine (except of icons - they must be copied locally or you have to set up `providers` manually). 
http://jsfiddle.net/qazpvtc5/

Have you inluded all of the necessary libs?

``` html
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/leaflet/0.7.3/leaflet-src.js"></script>
<script type="text/javascript" src="http://scanex.github.io/Leaflet-IconLayers/src/iconLayers.js"></script>
<script type="text/javascript" src="http://scanex.github.io/Leaflet-IconLayers/examples/providers.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet/0.7.3/leaflet.css">
<link rel="stylesheet" href="http://scanex.github.io/Leaflet-IconLayers/src/iconLayers.css">
```

By the way you can use `console.log` or developer's tools to debug your code instead of writing to dom element.

**Comment by chimaera8** [comment]
Hi there,

thanks for the hint. Indeed, something is wrong with my library import. I got it fixed, but I can still not import the iconLayers.js from my own webspace. As soon as I link to scanex.github, it's fine. I tried to replace it and watched for typos again and again, but nevermind. It's working for a start :)

Tanks again!
